name: Shellcheck

on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.sh"
      - ".github/workflows/shellcheck.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    name: shellcheck
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-shellcheck.yml@c3e3e0a44d4b79697f1babaa9bf287d1b264da52
    with:
      working-directory: .
